name: Frontend

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches: "develop"

jobs:
  build:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: client/node_modules
          key: ${{ runner.os }}-build-${{ e   
        working-directory: client
      - name: Build
        run: npm run build
        working-directory: client
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
