# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# name: Angular CI with NPM

# on:
#   push:
#     branches: [develop]
#   pull_request:
#     branches: [develop]

# jobs:
#   ci:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Set Up Node ${{ matrix.node-version }}
#       - uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"
#           cache-dependency-path: "**/package-lock.json"

#       - name: Install Dependencies
#         run: npm ci
#         working-directory: client

#       - name: Build
#         run: npm build --if-present
#         working-directory: client

name: Caching with npm
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

      # - name: Test
      #   run: npm test
